In [ ]:
# np.array
import numpy as np


In [ ]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [ ]:
#2D  and 3D array

In [ ]:
b = np.array([[1,2,3],[4,5,6,]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# with reshape

In [ ]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
np.arange(625).reshape(5,5,5,5)

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24]],

        [[ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74]],

        [[ 75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124]]],


       [[[125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134],
         [135, 1

In [ ]:
#np.ones and np.zeros
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((6,8
          m
          ))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4))  #no change in address while storing value

array([[0.62369165, 0.11062682, 0.2407095 , 0.21211531],
       [0.99066224, 0.56289312, 0.81460966, 0.04823849],
       [0.79637703, 0.27482946, 0.53810665, 0.31247341]])

In [ ]:
#np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
np.linspace(50,100,10,dtype=float)

array([ 50.        ,  55.55555556,  61.11111111,  66.66666667,
        72.22222222,  77.77777778,  83.33333333,  88.88888889,
        94.44444444, 100.        ])

In [ ]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#advance numpy

#array attributes   #here np.int32 means  compiler value in bytes

a1 = np.arange(10,dtype=np.int32)                       # 10 element ho jinka d type 32 bit ho
a2 = np.arange(12,dtype=float).reshape(3,4)             # 12 element ko reshape krna h float m
a3 = np.arange(8).reshape(2,2,2)                       #  8 ko arrange krna h 2 2 matrix m and  2 element k sath

print (a1)
print (a2)
print (a3)
print(type(a1))  l



[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
<class 'numpy.ndarray'>


In [ ]:
#ndim
a3.ndim

3

In [ ]:
#shape
print(a3.shape)

(2, 2, 2)


In [ ]:
np.full((4,5),7) # 4 row 5 column  m 7 ko arrange krna h

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])